name: first work flow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Greetings
    run: echo "Hello UK and World .. "
    - name : Print Good Bye
    run : ehco "Done - Bye .. Will do next Item"
